apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: oadp-operator
  name: backup1
spec:
  includedNamespaces:
    - my-database-app
  excludedResources:
    - imagetags.image.openshift.io
  snapshotVolumes: false
