= OpenShift Data Foundation Additional Features
//:toc:
//:toclevels: 4
:icons: font
:source-language: shell
:numbered:
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
:source-highlighter: pygments
//:hide-uri-scheme:

== Overview

The intent of this guide is to detail additional OpenShift Data Foundation (ODF)
some being considered Development Preview and undocumented
until a later version becomes available.

IMPORTANT: Starting April 2021, `OpenShift Container Storage` (OCS) has been rebranded
to `OpenShift Data Foundation` (ODF).

[start=1]
. *OpenShift Data Foundation 4.7*
.. *OSD BlueStore RocksDB metadata and WAL placement customization. (DP)* +
Learn how to create a custom *StorageCluster* to specify which devices are used for placing the OSD components.
.. *Mixed device type OSD. (DP)* +
Learn how to create a custom *StorageCluster* that uses mixed device types (HDD, SSD and NVMe).
.. *Ceph configuration override. (TP)* +
Learn how to pass custom Ceph parameters during your cluster deployment.
. *OpenShift Data Foundation 4.8*
.. *Data Segregation (DP).* +
Learn how to create a custom *Ceph Block Pool* with a custom CRUSH rule to restict access
to specific hosts or/and device types.

== ODF 4.7

include::ocs4-additionalfeatures-dbwal.adoc[]

include::ocs4-additionalfeatures-devtype.adoc[]

include::ocs4-additionalfeatures-override.adoc[]

== OSD 4.8

include::ocs4-additionalfeatures-segregation.adoc[]
