== Sample Application Deployment

In order to test failing over from one OCP cluster to another we need a simple application to and verify that replication is working.

Start by creating a new project on the *primary cluster*:

[source,role="execute"]
----
oc new-project my-database-app
----

Then use the `rails-pgsql-persistent` template to create the new application. The new `postgresql` volume will be claimed from the new *StorageClass*.

[source,role="execute"]
----
curl -s https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/training/modules/ocs4/attachments/configurable-rails-app.yaml | oc new-app -p STORAGE_CLASS=ocs-external-storagecluster-ceph-rbd-dr -p VOLUME_CAPACITY=5Gi -f -
----

After the deployment is started you can monitor with these commands.

[source,role="execute"]
----
oc status
----

Check the PVC is created.

[source,role="execute"]
----
oc get pvc -n my-database-app
----

This step could take 5 or more minutes. Wait until there are 2 *Pods* in
`Running` STATUS and 4 *Pods* in `Completed` STATUS as shown below.

[source,role="execute"]
----
watch oc get pods -n my-database-app
----
.Example output:
----
NAME                                    READY   STATUS      RESTARTS   AGE
pod/postgresql-1-deploy                 0/1     Completed   0          2m4s
pod/postgresql-1-r8j9z                  1/1     Running     0          2m2s
pod/rails-pgsql-persistent-1-build      0/1     Completed   0          2m5s
pod/rails-pgsql-persistent-1-deploy     0/1     Completed   0          35s
pod/rails-pgsql-persistent-1-hook-pre   0/1     Completed   0          33s
pod/rails-pgsql-persistent-1-tgvds      1/1     Running     0          23s

NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                              AGE
persistentvolumeclaim/postgresql   Bound    pvc-35f21284-cc83-479e-97db-3f778980908f   5Gi        RWO            ocs-external-storagecluster-ceph-rbd-dr   2m6s
----

You can exit by pressing kbd:[Ctrl+C].

Once the deployment is complete you can now test the application and the
persistent storage on ODF.

[source,role="execute"]
----
oc get route rails-pgsql-persistent -n my-database-app -o jsonpath --template="http://{.spec.host}/articles{'\n'}"
----

This will return a route similar to this one.

.Example output:
----
http://rails-pgsql-persistent-my-database-app.apps.ocp45.ocstraining.com/articles
----

Copy your route (different than above) to a browser window to create articles.

Click the `New Article` link.

Enter the `username` and `password` below to create articles and comments.
The articles and comments are saved in a PostgreSQL database which stores its
table spaces on the RBD volume provisioned using the
`ocs-storagecluster-ceph-rbd` *StorageClass* during the application
deployment.

----
username: openshift
password: secret
----

Once you have added a new article you can verify it exists in the `postgresql` database by issuing this command:

[source,role="execute"]
----
oc rsh -n my-database-app $(oc get pods -n my-database-app|grep postgresql | grep -v deploy | awk {'print $1}') psql -c "\c root" -c "\d+" -c "select * from articles"
----
.Example output:
----
You are now connected to database "root" as user "postgres".
                               List of relations
 Schema |         Name         |   Type   |  Owner  |    Size    | Description
--------+----------------------+----------+---------+------------+-------------
 public | ar_internal_metadata | table    | userAAF | 16 kB      |
 public | articles             | table    | userAAF | 16 kB      |
 public | articles_id_seq      | sequence | userAAF | 8192 bytes |
 public | comments             | table    | userAAF | 8192 bytes |
 public | comments_id_seq      | sequence | userAAF | 8192 bytes |
 public | schema_migrations    | table    | userAAF | 16 kB      |
(6 rows)

 id |           title            |                                                              body                                                              |         created_at         |         updated_at

----+----------------------------+--------------------------------------------------------------------------------------------------------------------------------+----------------------------+-----------------------
-----
  1 | Test Metro Multicluster DR | This article is to prove that we can restart the application in the OCP-DR cluster when the OCP-A cluster becomes unavailable. | 2021-04-13 22:17:53.602252 | 2021-04-13 22:17:53.60
2252
(1 row)
----
