name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: 'find . -name \'*.adoc\' | grep -i -v Readme | xargs asciidoctor -D "./docs"'
    - name: Save AsciiDoc step
      uses: actions/upload-artifact@v1
      with:
        name: documents
        path: docs/
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
